name: osp
services:
  db:
    image: mysql:8.0
    container_name: osp_db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped

  redis:
    container_name: osp_redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
volumes:
  dbdata:
