# reusable workflow for build app
name: build

on: workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-20.04
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version: 7
    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: "18.x"
        cache: 'pnpm'
    
    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm run build

    - name: Create deployment artifact
      run: tar -czf osp_${{github.sha}}.tar.gz --exclude=".git" --exclude="node_modules" *

    - name: Store artifact for distribution
      uses: actions/upload-artifact@v3
      with:
        name: app-build
        path: osp_${{github.sha}}.tar.gz

  prepare-release-on-server:
    runs-on: ubuntu-20.04
    needs: build
    steps:
    - name: Get artifact from previous step
      uses: actions/download-artifact@v3
      with:
        name: app-build
        path: osp_${{github.sha}}.tar.gz
    - name: Doorkeeper open
      uses: patoroco/doorkeeper@master
      with:
        digitaloceanToken: ${{ secrets.DO_TOKEN }}
        firewallName: web-firewall
        actionToDo: "add"
        dryRun: false
    - name: Upload to staging server
      uses: appleboy/scp-action@master
      with:
        src: osp_${{github.sha}}.tar.gz
        dest: /var/www/${{secrets.STAGING_SERVER}}/html/artifacts/osp_${{github.sha}}.tar.gz
        host: ${{secrets.STAGING_SERVER}}
        port: 22
        user: ${{ secrets.STAGING_USER }}
        privateKey: ${{ secrets.DEPLOY_SSH_KEY }}
    
