name: doorkeer_test

on: workflow_dispatch

jobs:
  open:
    runs-on: ubuntu-20.04
    steps:
    - name: Doorkeeper open
      uses: patoroco/doorkeeper@master
      with:
        digitaloceanToken: ${{ secrets.DO_TOKEN }}
        firewallName: web-firewall
        actionToDo: "add"
        protocol: "tcp"
        port: 2200
        dryRun: false
